### PR TITLE
centos-ci: Init job to build and test GlusterD2

### PR DESCRIPTION
**Pull request by kshlm**
The job xml file will be added in the next commit.

### CODE REVIEW

**Comment by kshlm** [comment]
Don't merge yet. I've opened this PR to get a place to access the scripts needed by the job.
Once I've tested the job, I'll add the job xml another commit.

**Comment by kshlm** [comment]
This is ready for merge now. The job correctly works.
The failure needs to be fixed in glusterd2.

**Comment by kshlm** [comment]
@nixpanic @nigelbabu Could one of you merge this? Once this is merged, I can continue fixing the failures.

**Comment by nigelbabu** [comment]
One for @nixpanic. I'm not familiar enough with Centos CI to comment.

**Pull request merged**
