### PR TITLE
Move to Fedora 24 for rpm jobs (Bug 1364880)

### PR DESCRIPTION
**Pull request by nigelbabu**

### CODE REVIEW

**Comment by kshlm** [comment]
:+1: I thought you were upgrading the slaves. Just one question though.

The builders for this job are running el6. So, can mock build packages for newer releases on older machines?

**Comment by kshlm** [comment]
I guess it should work. EL6 is much older than F22, and mock still built the packages.

**Comment by mscherer** [comment]
I think we can ask to the Fedora team, as this was a issue in the past due to rpm changes. I am fully ok on the principal, but kshlm is right, maybe we might hit issues  in the future. But then, it shouldn't be too hard to install a working Fedora builder.

**Comment by nigelbabu** [comment]
Worst case scenario we can get one builder on F24 just to do package building (maybe on our new infra?). It takes very little time for the job anyway.

**Comment by nigelbabu** [comment]
Talked to @nixpanic and he says this looks good. Merging it.

**Pull request merged**
