### PR TITLE
handle_github: add a check for experimental branch

### PR DESCRIPTION
**Pull request by amarts**
Signed-off-by: Amar Tumballi <amarts@redhat.com>

### CODE REVIEW

**Comment by amarts** [comment]
@nigelbabu @deepshikhaaa Need you to test it please, couldn't test it in actual setup. Dry run was fine. But not sure if the job passes the proper GERRIT_BRACH here. Would be great to get this going.

@ShyamsundarR

**Comment by amarts** [comment]
Can this be merged? So that we can fix the failure on experimental branch.

**Comment by nigelbabu** [comment]
Can you add a test in the test file for this scenario?

**Comment by amarts** [comment]
Couldn't find a way to Mock the GERRIT_BRANCH part in argument. Will see what I can do.

**Comment by nigelbabu** [comment]
Merged by hand because I sat down to write a test: https://github.com/gluster/glusterfs-patch-acceptance-tests/commit/b532ce8a16b393f80a64f159a689206dd5356f2f

**Pull request closed without merging**
